{% set version = "2.12" %}

package:
  name: liburing
  version: {{ version }}

source:
  url: https://github.com/axboe/liburing/archive/liburing-{{ version }}.tar.gz
  sha256: f1d10cb058c97c953b4c0c446b11e9177e8c8b32a5a88b309f23fdd389e26370

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('liburing', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make

test:
  commands:
    - test -f "$PREFIX/include/liburing.h"
    - test ! -f "$PREFIX/lib/liburing.a"
    - test -f "$PREFIX/lib/liburing.so"
    - test -f "$PREFIX/lib/pkgconfig/liburing.pc"
    - test ! -f "$PREFIX/lib/liburing-ffi.a"
    - test -f "$PREFIX/lib/liburing-ffi.so"
    - test -f "$PREFIX/lib/pkgconfig/liburing-ffi.pc"

about:
  home: https://github.com/axboe/liburing
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Efficient IO with io_uring
  description: |
    liburing provides helpers to setup and teardown io_uring instances, and
    also a simplified interface for applications that don't need (or want) to
    deal with the full kernel side implementation.
  doc_url: https://kernel.dk/io_uring.pdf
  dev_url: https://github.com/axboe/liburing

extra:
  recipe-maintainers:
    - davidbrochart
