{% set version = "2.5" %}

package:
  name: liburing
  version: {{ version }}

source:
  url: https://github.com/axboe/liburing/archive/liburing-{{ version }}.tar.gz
  sha256: 456f5f882165630f0dc7b75e8fd53bd01a955d5d4720729b4323097e6e9f2a98

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('liburing', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f "$PREFIX/include/liburing.h"
    - test ! -f "$PREFIX/lib/liburing.a"
    - test -f "$PREFIX/lib/liburing.so"
    - test -f "$PREFIX/lib/pkgconfig/liburing.pc"
    - test ! -f "$PREFIX/lib/liburing-ffi.a"
    - test -f "$PREFIX/lib/liburing-ffi.so"
    - test -f "$PREFIX/lib/pkgconfig/liburing-ffi.pc"

about:
  home: https://github.com/axboe/liburing
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Efficient IO with io_uring
  description: |
    liburing provides helpers to setup and teardown io_uring instances, and
    also a simplified interface for applications that don't need (or want) to
    deal with the full kernel side implementation.
  doc_url: https://kernel.dk/io_uring.pdf
  dev_url: https://github.com/axboe/liburing

extra:
  recipe-maintainers:
    - davidbrochart
